spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ormdb
    user: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # H2 ?? ??
        format_sql: true
        show-sql: true # sql? ?? ???
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.sql: debug